workflows:
  ios-workflow:
    name: iOS TestFlight Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        APP_KEY_VALUE: "default_app_key_here"
      flutter: stable
      xcode: latest
      cocoapods: default

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true

    scripts:
      - name: Set up code signing
        script: |
          keychain initialize
          # Fetch certificates and profiles from Apple
          # app-store-connect fetch-signing-files "com.lawbug.wagetimekeeper" --project-id "$APP_STORE_CONNECT_PROJECT_ID" --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" --key-id "$APP_STORE_CONNECT_KEY_ID" --private-key "$APP_STORE_CONNECT_PRIVATE_KEY"
          # keychain add-certificates
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Build Flutter IPA
        script: |
          flutter build ipa --release --no-codesign --dart-define=APP_KEY_VALUE=$APP_KEY_VALUE
    artifacts:
      - build/ios/ipa/*.ipa

  web-workflow:
    name: Web PWA Build
    instance_type: mac_mini_m1
    max_build_duration: 30
    environment:
      groups:
        - github
      vars:
        APP_KEY_VALUE: "default_app_key_here"
      flutter: stable


    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true

    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Build Flutter Web
        script: |
          flutter build web --release --base-href "/PWT-test/" --dart-define=APP_KEY_VALUE=$APP_KEY_VALUE
      - name: Publish to GitHub Pages
        script: |
          cd build/web
          git init
          git config user.name "Codemagic"
          git config user.email "builder@codemagic.io"
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push --force https://nomefu:$GITHUB_TOKEN@github.com/NoMeFU/PWT-test.git master:gh-pages

    artifacts:
      - build/web/**
