// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5DwzmYyePrrIPeRRVu2bKFM7cbAX4z2I',
    appId: '1:755247727348:web:71e21b7770857201dc14a1',
    messagingSenderId: '755247727348',
    projectId: 'prevailing-wage-timekeeper',
    authDomain: 'prevailing-wage-timekeeper.firebaseapp.com',
    storageBucket: 'prevailing-wage-timekeeper.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5DwzmYyePrrIPeRRVu2bKFM7cbAX4z2I',
    appId: '1:755247727348:android:a5d97462f46c02a7dc14a1',
    messagingSenderId: '755247727348',
    projectId: 'prevailing-wage-timekeeper',
    storageBucket: 'prevailing-wage-timekeeper.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9D5Ff7W1pW_FU8t9OoqVwZedN6bRYfn0',
    appId: '1:755247727348:ios:f3e92769a43bd764dc14a1',
    messagingSenderId: '755247727348',
    projectId: 'prevailing-wage-timekeeper',
    storageBucket: 'prevailing-wage-timekeeper.firebasestorage.app',
    androidClientId: '755247727348-3fafco3modqlbhh0db1mja73tif14826.apps.googleusercontent.com',
    iosClientId: '755247727348-f1151369mc4gn2gh0u8eder9cr1epvgh.apps.googleusercontent.com',
    iosBundleId: 'com.lawbug.wagetimekeeper',
  );

}